import "@radix-ui/themes/styles.css";
import './theme-config.css'
import './globals.css';
import type { Metadata } from 'next';
import { Container, Theme } from "@radix-ui/themes";
import NavBar from './NavBar';
import { Suspense } from "react";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from './QueryClientProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <head>
        {/* Load Inter from Google Fonts instead of next/font to avoid turbopack internal font issues */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap" rel="stylesheet" />
      </head>
      <body className="font-inter">
        <QueryClientProvider>
          <AuthProvider>
            <Theme accentColor="purple" radius="large" scaling="90%">
              <NavBar />
              <main className="p-5">
                <Suspense fallback={
                  <div className="flex justify-center items-center h-64">
                    <div>Loading...</div>
                  </div>
                }>
                  <Container>
                    {children}
                  </Container>
                </Suspense>
              </main>
            </Theme>
          </AuthProvider>
        </QueryClientProvider>

      </body>

    </html>
  )
}
